on:
  pull_request:
  push:
    branches:
      - main
name: CI
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2']
    container:
      image: ghcr.io/city-of-helsinki/drupal-php-docker:${{ matrix.php-versions }}-alpine

    services:
      db:
        image: mysql:8
        env:
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
          MYSQL_DATABASE: drupal
          MYSQL_ROOT_PASSWORD: drupal
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install required composer dependencies
        run: composer install

      - name: Run PHPCS
        run: vendor/bin/phpcs --ignore=*/vendor/*,*/sut/* .

      - name: Run phpstan
        run: vendor/bin/phpstan analyze -c phpstan.neon .

      - name: Run PHPUnit tests
        run:
          vendor/bin/phpunit -c tests/phpunit.xml tests/

      - name: Upload codecov
        run: codecov

