on:
  pull_request:
  push:
    branches:
      - main
name: CI
env:
  SYMFONY_DEPRECATIONS_HELPER: disabled
  BROWSERTEST_OUTPUT_DIRECTORY: 'public/sites/simpletest'
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2']
    container:
      image: ghcr.io/city-of-helsinki/drupal-php-docker:${{ matrix.php-versions }}-alpine

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install required composer dependencies
        run: composer install

      - name: Run PHPCS
        run: |
          vendor/bin/phpcs . --standard=Drupal --extensions=php,module,inc,install,test,info

      - name: Run PHPUnit tests
        run: |
          vendor/bin/phpunit \
            --bootstrap tests/bootstrap.php \
            -c tests/phpunit.xml \
            --coverage-clover=coverage.xml
          codecov
